### ISSUE TITLE
multiplying verts on conversion from csg model to unity mesh

### ISSUE THREAD

**Issue by MagnusZane** [karl-/pb_CSG#1]
I wanted to use this in my application, but I found that when you perform a subtraction and it converts back from the model to a unity mesh, it multiplies the verticies by a good bit.... how can we avoid shit and get rid of the extra verticies when we convert back?

**Comment by karl-** [comment]
The extra vertices are part of the process.  To clean up the topology you'll need to use another library, or do it manually.
