### ISSUE TITLE
Are there any import instructions?

### ISSUE THREAD

**Issue by Hanousi** [karl-/pb_CSG#13]
Hey, I'm new to using Unity and was wondering if you could include instructions in the readme.md about how to import the library into a Unity project, that would be awesome!

Thank you very much,
Hani

**Comment by karl-** [comment]
This repository is a package, so you can either clone it into your Packages directory or add it from the Package Manager with the git url.

**Comment by Hanousi** [comment]
Thank you very much for the response!

**Comment by andybak** [comment]
If it's a package then you should probably remove ProjectSettings
