### ISSUE TITLE
2D drawing from 3d 

### ISSUE THREAD

**Issue by aymenbs2** [karl-/pb_CSG#16]
Hello man you are awsome i have a question can you help me to draw 2d from 3d object like cad software using unity and thanks

**Comment by bhupiister** [comment]
@aymenbs2 I have the same question. I am looking for 2d drawing with hidden line removal and objects hiding which are behind other object. 

Did you find the solution ?

**Comment by karl-** [comment]
This isn't something that would be covered by the library. ProBuilder could probably help though https://docs.unity3d.com/Packages/com.unity.probuilder@5.0/api/UnityEngine.ProBuilder.PolyShape.html#methods
