### ISSUE TITLE
Mesh substraction results in non centered mesh

### ISSUE THREAD

**Issue by nobrainstudio** [karl-/pb_CSG#19]
If I substract a cube from another one like this 
![image](https://user-images.githubusercontent.com/72552046/108845021-31e14080-75dd-11eb-87cf-69b736f44395.png)

Depending on the cutter mesh position it will result in a non centered mesh with an offset corresponding to the original meshToCut position

![image](https://user-images.githubusercontent.com/72552046/108845087-458ca700-75dd-11eb-892c-e60fa747af03.png)

My MeshCutter is on the CubeCutter and looks like this 

![image](https://user-images.githubusercontent.com/72552046/108845274-7c62bd00-75dd-11eb-8256-d2159b04bc97.png)

Thank you for your help !

**Comment by karl-** [comment]
The mesh is returned in world space coordinates. If you're assigning the mesh back to one of the source GameObjects you will need to reset the transform to identity.
