### ISSUE TITLE
Example code doesn't work, ends up with seemingly empty mesh.

### ISSUE THREAD

**Issue by M0rph3v5** [karl-/pb_CSG#2]

**Comment by karl-** [comment]
Using Unity 5.3.0f4 I'm able to run the demo scene without any issue.  Can you provide a little more information about what code exactly isn't working, and what version/target platform you're running?

**Comment by M0rph3v5** [comment]
Seems like you need to assign a material to the renderer again afterwards, that seems to be missing in your readme! :)

**Comment by karl-** [comment]
Ah, okay.  I've added that to the example code in the readme, thanks for clarifying.
