### ISSUE TITLE
The name 'CSG' does not exist in the current context

### ISSUE THREAD

**Issue by localhosted** [karl-/pb_CSG#25]
I imported the project via the git url, but when I try to use it I get these errors:

> Assets\Scripts\ShatterExample.cs(34,24): error CS0103: The name 'CSG' does not exist in the current context

> Assets\Scripts\ShatterExample.cs(34,9): error CS0246: The type or namespace name 'Model' could not be found (are you missing a using directive or an assembly reference?)

**Comment by karl-** [comment]
This package uses assembly definitions. You need to reference the CSG asmdef in your own assembly definition.

https://docs.unity3d.com/Manual/cus-asmdef.html

**Comment by miguelcanosantana** [comment]
Although this issue is closed, I think it would be nice if in the readme was a guide to do this for newcomers. I'm currently a bit stuck with the process.
