### ISSUE TITLE
Complete PR

### ISSUE THREAD

**Issue by giovanniani** [karl-/pb_CSG#34]
I was trying to use this library in unity 2021 and the Visual Studio said that the "CSG " name does not exist in the namespace.

I went to look for the PR files to see if maybe that was a solution and it worked.

I just don't anyone else to have to go thorugh that struggle, since the PR fix edit.

Thanks again for this library, is helping me a lot!

**Comment by Furgl** [comment]
I'm encountering the same issue with Unity 2021 and Visual Studio saying that "CSG" does not exist. 

What was the solution for this? What do you mean by PR files?

Thanks!

**Comment by giovanniani** [comment]
Si if you go to the Pull request page on the repository, the last Pull request has two file changes.
Replace those ones with those from the PR

On Feb 1, 2023, at 12:50, Furgl ***@***.***> wrote:

﻿

I'm encountering the same issue with Unity 2021 and Visual Studio saying that "CSG" does not exist.

What was the solution for this? What do you mean by PR files?

Thanks!

**Comment by karl-** [comment]
Merged https://github.com/karl-/pb_CSG/pull/33
