### ISSUE TITLE
Check out my Repo for the best version with my own implementation, bug fixes and improvements

### ISSUE THREAD

**Issue by strangeways-dev** [karl-/pb_CSG#39]
EDIT: I have made my repo private because since I uploaded it I have made so many changes and adaptations, and added my own implementations, I have fixed EVERYTHING, I can't believe it... years ago when I first touched this thing it seamed like an impossible feat, I was nowhere near knowledgeable enough to make it happen. I gave up but lately I was drawn back in and I found a way. I plan on selling my adaptation and implementation on the Unity Asset store, I'm so extremely happy with the results and I can't wait to share them and its potentials. I thought about giving it away for free but I have put so much time and effort in to the things that I do and I have nothing to show for it and I think it's about time I reap what I've sown so I can invest in my future and in to other projects I have big visions for.
I will come back when it's available.

**Comment by karl-** [comment]
Congrats. However, if your project is not open source I'd kindly ask that you please not use this repository to advertise.
