### ISSUE TITLE
TLS Allocator ALLOC_TEMP_TLS, underlying allocator ALLOC_TEMP_MAIN has unfreed allocations, size 96

### ISSUE THREAD

**Issue by Qiming0303** [karl-/pb_CSG#41]
Hey everyone, after using the CGS, the console keep print:

TLS Allocator ALLOC_TEMP_TLS, underlying allocator ALLOC_TEMP_MAIN has unfreed allocations, size 96
Internal: Stack allocator ALLOC_TEMP_MAIN has unfreed allocations, size 96
To Debug, enable the define: DEBUG_STACK_LEAK in StackAllocator.h. This will output the callstacks of the leaked allocations

my Unity version is 2021.3.0f1

Do you have any insights for solving this? Huge thanks in advance.

**Comment by karl-** [comment]
This looks unrelated to me, but it's difficult to say without more context. Do you have an editor log you could share?
