### ISSUE TITLE
Subtraction does not work on 2d meshes

### ISSUE THREAD

**Issue by padmalcom** [karl-/pb_CSG#5]
I created 2 planar 2d meshes and tried to subtract one from the other. In the method CSG_Node.Subtract, CSG_Node a.AllPolygons returns an empty list. Using 3d meshes it works. Union and Intersect work fine.

**Comment by nogoba286** [comment]
Unity doesn't natively support 2D Boolean operations, but libraries like Clipper or LibTess2 can help. These libraries are designed for 2D polygon operations.

Steps:
1.Import a 2D Boolean library like Clipper.
2.Convert your 2D meshes into polygons.
3.Perform the subtraction operation using the library.
4.Convert the resulting polygons back into Unity meshes.

**Comment by padmalcom** [comment]
Thank you, I used Clipper.
