### ISSUE TITLE
Error with subtraction

### ISSUE THREAD

**Issue by Thespyinthehole** [karl-/pb_CSG#8]
I have made my own cube meshes and when I try to do a subtraction i get this error.

IndexOutOfRangeException: Array index is out of range.
Parabox.CSG.CSG_Model..ctor (UnityEngine.GameObject go) (at Assets/CSG/Classes/CSG_Model.cs:39)
Parabox.CSG.CSG.Subtract (UnityEngine.GameObject lhs, UnityEngine.GameObject rhs) (at Assets/CSG/CSG.cs:62)

**Comment by zieglerkevin** [comment]
I had the same issue yesterday. You need to make sure to supply UVs and possibly colors, too.
Alternatively you could modify that line so it checks for UVs etc properly.

**Comment by karl-** [comment]
Should be fixed as of e2d2e1d, please re-open if not addressed.
